feat: provide scores in sbom details response
trustification/trustify pull request #1005
Opened 2024-11-14 13:56 UTC by dejanb

This is the first attempt in resolving #952

2024-11-14 14:21 UTC, carlosthe19916 requested changes
@dejanb thanks for putting this PR in place.

Generally speaking this is exactly what I need so I would be happy to have this PR merged but here are some things I've just notice that we might need to address before:

- I've uploaded the files from D3 https://github.com/trustification/trustify/tree/main/etc/datasets/ds3
- Then try to hit the endpoint `http://localhost:8080/api/v1/sbom/{id}/advisory` and the response is huge. The one I got has 40Mb of size which I think is too much.
  - I guess the size of the response could be explained because the response includes `status.vulnerability.advisories` where `advisories` is the field that weights the most. From the top of my mind I would suggest removing `status.vulnerability.advisories` so the response is not that huge but I am not sure if that is fine with you.

2024-11-14 14:28 UTC, dejanb commented
Yeah, as mentioned in the issue, I think we should actually return [VulnerabilitySummary](https://github.com/trustification/trustify/blob/main/modules/fundamental/src/vulnerability/model/summary.rs#L17) here, but that needs a bit more changes to fetch for a single vulnerability. It should be faster as well as it will not reach database to fetch unnecessary data.

2024-11-21 00:33 UTC, jcrossley3 commented
I took a swipe at it, using `VulnerabilityHead` instead of `VulnerabilityDetails` and adding a `severity` field. 

Can you give it a shot @carlosthe19916 and see if we're any closer to what you need? Hoping to add some unit tests tomorrow.

2024-11-21 12:45 UTC, carlosthe19916 commented
@jcrossley3 Thank you very much!!!!!
This reduced the number of call drastically and I was able to generate the Dashboard using my WIP draft PR https://github.com/trustification/trustify-ui/pull/232

![image](https://github.com/user-attachments/assets/a61c7f07-c586-4526-bf47-e97c6b968916)

- From the pure point of view "It Works". I think YESSS it works your changes gives me back what I need. We can call it DONE. Thanks.
- From the point of long term API:
  - If I hit `/api/v1/sbom/{id}/advisory` then the response is similar to:

```json
[
    {        
        "status": [
            {
                "vulnerability": {
                    "normative": true,
                    "identifier": "CVE-2023-20860",
                    "title": null,
                    "description": null,
                    "reserved": null,
                    "published": null,
                    "modified": null,
                    "withdrawn": null,
                    "discovered": null,
                    "released": null,
                    "cwes": []
                },
                "severity": "high",
                "status": "not_affected",                
            },
```

You can see that the field `severity` is outside of the `vulnerability` object. However, if I hit `/api/v1/vulnerability/{id}` then the severity is in a field named `average_severity` and it is inside the object itself (a vulnerability).

```json
{
  "title": "string", 
  "average_severity": null,
// other fields
}
```

I assume `average` and `average_severity` are the same in this case.

In the long term, the APIs always grow, and having a strategy for having consistency and avoiding fields to be spread in different places and with different names would be necessary for the future. 

For the time being, I am happy to accept this PR as it is because it will allow me to have the Dashboard being implemented! Thank you!

2024-11-21 13:23 UTC, jcrossley3 commented
> @jcrossley3 Thank you very much!!!!! This reduced the number of call drastically and I was able to generate the Dashboard using my WIP draft PR [trustification/trustify-ui#232](https://github.com/trustification/trustify-ui/pull/232)

Good to hear! :smile: 

> You can see that the field `severity` is outside of the `vulnerability` object. However, if I hit `/api/v1/vulnerability/{id}` then the severity is in a field named `average_severity` and it is inside the object itself (a vulnerability).

I can fix that. I'll flatten all the fields and rename `severity` to `average_severity`.

> For the time being, I am happy to accept this PR as it is because it will allow me to have the Dashboard being implemented! Thank you!

Part of the reason it took me so long to grok this part of the code is its lack of unit tests, so I'd like to fill some in there and clean up the code a bit. Hoping to have that in today, if that's not too long for you to wait for the merge.

2024-11-21 15:58 UTC, carlosthe19916 commented
I can wait surely. Thanks @jcrossley3 !

2024-11-21 19:27 UTC, jcrossley3 commented
@carlosthe19916 I refactored things a bit and flattened the structure per your request -- lemme know if it needs further tweaking

@dejanb I would've requested a review from you but since you originated the PR, I can't :shrug:

2024-11-22 09:42 UTC, ctron approved these changes
Love all the improvements!

2024-11-22 09:42 UTC, ctron commented on cvss/src/cvss3/score.rs
> +        match self.0 {
:heart:

2024-11-22 09:50 UTC, dejanb reviewed
It looks good to me. The UI is currently broken as sbom/vulnerability page still expects the old response. Maybe we should wait with merging until UI catches up? @carlosthe19916

2024-11-22 11:12 UTC, carlosthe19916 commented
@jcrossley3 Thanks, I've tested it and it works as expected. Whenever you feel it is the time let's merge this PR.

2024-11-22 12:18 UTC, carlosthe19916 approved these changes

2024-11-22 12:34 UTC, merged