chore: allow running a dedicated importer instance
trustification/trustify pull request #1063
Opened 2024-11-29 15:51 UTC by ctron

2024-12-03 18:08 UTC, jcrossley3 requested changes

2024-12-03 18:08 UTC, jcrossley3 commented on server/src/profile/importer.rs
> +pub struct Run {
To me, it's confusing to have both this module *and* the server's `with_importer` argument. I would think one or the other would suffice.

My vote would be for keeping just the `with_importer` feature of the server and delete this module. To run a dedicated importer, we'd simply set the `with_importer` to true on one of the deployed `api` servers.

2024-12-03 18:08 UTC, jcrossley3 commented on trustd/src/main.rs
> +    let importer = Trustd::parse_from([
Wouldn't it be simpler to add `--with-importer` to the `api` var and omit the `importer` var?

2024-12-04 07:18 UTC, ctron commented
The idea was to split up the "all-in-one" thing into two processes/instances: one running the importer, one running the API server.

I think, right now, we're overloading the `api` sub-command. We have the `db` sub-commands, but enable that functionality with the `--devmode` on the `api` sub-command. Running the importers on the `api` sub-command also feels wrong. Then we also have the "no subcommand" mode, which does run the DB stuff, as well as the API server.

I think it's ok to have an "all in one" command. But adding more complexity to the `api` sub-command feels wrong. Then again, forcing people today to run two processes, if they only want to use the `api` sub-command felt like leading to frustration.

That was the reasoning behind having both the dedicated command, as well as the "with" flag.

If we want to approach this from a perspective of making this clean and focused, I think we should drop the "with" flag on the API server, and run this together with the API server when running in "pm mode".

2024-12-04 14:25 UTC, jcrossley3 commented
> If we want to approach this from a perspective of making this clean and focused, I think we should drop the "with" flag on the API server, and run this together with the API server when running in "pm mode".

+1

2024-12-05 13:03 UTC, ctron commented
@jcrossley3 I updated the PR, I hope that's what you had in mind.

2024-12-05 13:30 UTC, jcrossley3 approved these changes

2024-12-05 13:47 UTC, merged