Add SBOM version, fix SBOM listing
trustification/trustify pull request #419
Opened 2024-06-18 06:57 UTC by ctron

The main motivation of this PR is to fix issue #284, adding an SBOM version to the response.

For CycloneDX there can be a dedicated version of the main component of the SBOM. For SPDX, there can exist one or more packages describing the SBOM, which may include the version information.

So the information which can be provides is a "described_by" set of packages per SBOM, which contains CPEs, PURLs, a name and an optional version information. However, this set can also be empty.

During work in this issue I discovered another one (#414), where instead of returning all SBOMs, the endpoint returned all SBOM nodes. This is also fixed as part of this PR.

2024-06-18 07:07 UTC, ctron commented
cc @carlosthe19916

2024-06-20 18:48 UTC, jcrossley3 requested changes

2024-06-20 18:48 UTC, jcrossley3 commented on migration/src/m0000250_create_sbom_package.rs
> +                    .col(ColumnDef::new(SbomPackage::Version).string())
Please create a new migration for this.

2024-06-21 06:09 UTC, ctron commented
Looks like this got merged in via #424. I'll create a follow up PR.

2024-06-21 06:09 UTC, closed without merging