Wire up the full ClearlyDefined definition importer from their blobst…
trustification/trustify pull request #882
Opened 2024-10-02 16:08 UTC by bobmcwhirter

…ore.

2024-10-03 14:30 UTC, jcrossley3 reviewed
I don't understand why we need both a `ClearlyDefinedLoader` taking a `Value` and a `ClearlyDefinedCurationLoader` taking a `Curation`.

I'm not familiar enough with the walker interfaces, so I'll defer to @ctron on that.

2024-10-03 14:38 UTC, bobmcwhirter commented
> I don't understand why we need both a `ClearlyDefinedLoader` taking a `Value` and a `ClearlyDefinedCurationLoader` taking a `Curation`.

The `Curation` YAML was fairly small/easy to make a `serde` impl for.

The `Definition` JSON is more complex, and since we're just plucking a few small bits out of it, figured JsonPath was sufficient against `Value`.

tl;dr: lazy

2024-10-04 07:56 UTC, ctron requested changes
A few small things.

2024-10-04 07:56 UTC, ctron commented on modules/importer/src/runner/clearly_defined/walker.rs
> +        let changes = reqwest::get(self.changes_index_url()).await?;
This creates a new connection pool for each request. I think we should create and keep a client.

Same for the other calls.

2024-10-04 07:56 UTC, ctron commented on modules/ingestor/src/service/sbom/clearly_defined.rs
> +        println!("{:#?}", item);
No `println` please.

2024-10-04 13:40 UTC, ctron approved these changes

2024-10-04 14:05 UTC, merged